language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

install: script/bootstrap
script: script/cibuild

# deploy to gh_pages branch 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: e94b75c30abfaae321fbf19e77487b1781b0af33
  on:
    branch: master
