language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

install: script/bootstrap
script: script/cibuild

# deploy to gh_pages branch 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6d97298f4f2089c1a71d64d36fde9de17aaea896
  on:
    branch: master
