language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

install: script/bootstrap
script: script/cibuild

# deploy to gh_pages branch 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $2346ede5e0e809fca926096f611254ee85d70aea
  on:
    branch: master
